name: Checkout

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: failure()
        with:
            name: cypress-screenshots
            path: cypress/screenshots
            if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to warn
      - uses: actions/upload-artifact@v4
        if: always()
        with:
            name: cypress-videos
            path: cypress/videos
            if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to warn